const name = document.querySelector('#name')
console.log(name)
const paragraph = document.querySelector('.par')
console.log(paragraph)
const buttton = document.querySelector('button')
console.log(buttton)